# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonStat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStat.setObjectName("pushButtonStat")
        self.verticalLayout.addWidget(self.pushButtonStat)
        self.pushButtonBioeq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBioeq.setObjectName("pushButtonBioeq")
        self.verticalLayout.addWidget(self.pushButtonBioeq)
        self.pushButtonPred = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPred.setObjectName("pushButtonPred")
        self.verticalLayout.addWidget(self.pushButtonPred)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.PathToFileButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.PathToFileButton.setIconSize(QtCore.QSize(50, 50))
        self.PathToFileButton.setObjectName("PathToFileButton")
        self.verticalLayout_2.addWidget(self.PathToFileButton)
        self.pushButtonDone = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.verticalLayout_2.addWidget(self.pushButtonDone)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonStat.setText(_translate("MainWindow", "STATISTICS"))
        self.pushButtonBioeq.setText(_translate("MainWindow", "BIOEQ"))
        self.pushButtonPred.setText(_translate("MainWindow", "PREDICTION"))
        self.PathToFileButton.setText(_translate("MainWindow", "Please, choose file "))
        self.pushButtonDone.setText(_translate("MainWindow", "Done"))
