# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThirdWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MetricsWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        MainWindow.setToolTipDuration(5)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(450, 400, 113, 32))
        self.pushButtonNext.setToolTipDuration(10)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(340, 400, 113, 32))
        self.pushButtonBack.setToolTipDuration(10)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 411, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxCount = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxCount.setObjectName("checkBoxCount")
        self.verticalLayout.addWidget(self.checkBoxCount)
        self.checkBoxMean = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxMean.setObjectName("checkBoxMean")
        self.verticalLayout.addWidget(self.checkBoxMean)
        self.checkBoxStd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxStd.setObjectName("checkBoxStd")
        self.verticalLayout.addWidget(self.checkBoxStd)
        self.checkBoxMax = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxMax.setObjectName("checkBoxMax")
        self.verticalLayout.addWidget(self.checkBoxMax)
        self.checkBoxMin = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxMin.setObjectName("checkBoxMin")
        self.verticalLayout.addWidget(self.checkBoxMin)
        self.checkBoxQuants = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxQuants.setObjectName("checkBoxQuants")
        self.verticalLayout.addWidget(self.checkBoxQuants)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonNext.setText(_translate("MainWindow", "Next"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.checkBoxCount.setText(_translate("MainWindow", "объем выборки"))
        self.checkBoxMean.setText(_translate("MainWindow", "среднее по фиче"))
        self.checkBoxStd.setText(_translate(
            "MainWindow", "стандартное отклонение по фиче"))
        self.checkBoxMax.setText(_translate("MainWindow", "максимальное"))
        self.checkBoxMin.setText(_translate("MainWindow", "минимальное"))
        self.checkBoxQuants.setText(_translate(
            "MainWindow", "стандратные квантили"))
