# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GraphsWindowCross(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 461, 51))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 150, 421, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxLogAllinGroup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxLogAllinGroup.setObjectName("checkBoxLogAllinGroup")
        self.verticalLayout.addWidget(self.checkBoxLogAllinGroup)
        self.checkBoxAllinGroup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxAllinGroup.setObjectName("checkBoxAllinGroup")
        self.verticalLayout.addWidget(self.checkBoxAllinGroup)
        self.checkBoxLogForEachGroup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxLogForEachGroup.setObjectName("checkBoxLogForEachGroup")
        self.verticalLayout.addWidget(self.checkBoxLogForEachGroup)
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(460, 420, 113, 32))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(330, 420, 113, 32))
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Выберите таблицы, Вы которые хотели бы увидеть:</span></p></body></html>"))
        self.checkBoxLogAllinGroup.setText(_translate("MainWindow", "Индивидуальные графики для пациентов, где изображена \n"
" концентрация обоих препаратов"))
        self.checkBoxAllinGroup.setText(_translate("MainWindow", "Графики, на которых показаны средние концентрации \n"
" обоих препаратов по группам"))
        self.checkBoxLogForEachGroup.setText(_translate("MainWindow", "График, где данные обобщены по двум препаратам"))
        self.pushButtonNext.setText(_translate("MainWindow", "Вперед"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
